= Dokumentation Proxmox Server
:toc:

== Installation und Konfiguration Proxmox Node 

Die Installation erfolgt in einer Virtuellen Maschine (z.B. Hyper-V, QEMU, Virtual Box), wobei bei der Verwendung von Hyper-V gewisse Einstellungen vorgenommen werden müssen (s.u.). In der Realität würde ein dedizierter Server für Proxmox verwendet werden, keine VM. Für kleinere Installationen ist ein Laptop z.B. ausreichend, es sollte auf ausreichend RAM und Speicherplatz geachtet werden.

Das ISO Image zur Installation kann hier heruntergeladen werden: 

https://www.proxmox.com/de/downloads/proxmox-virtual-environment/iso

=== Paketquellen

Bei der Verwendung von `apt` kommt es zu Fehlermeldungen aufgrund nicht signierter Repos. Dies liegt an der fehlenden Subscription für Proxmox. Proxmox ist aber auch ohne Subscription zu nutzen. Es müssen nur die entsprechenden _No-Subscription_ Repos eingetragen werden. Die Pakete darin sind im Vergleich nicht so ausgiebig getestet und der Betrieb wird für Produktivsysteme nicht empfohlen.

Folgende Einträge in den beiden Dateien vorhehmen und die enthaltenen Repo-Links löschen oder auskommentieren:

./etc/apt/sources.list.d/pve-enterprise.list
----
deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
----

./etc/apt/sources.list.d/ceph.list
----
deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription
----

Links:

- https://pve.proxmox.com/wiki/Package_Repositories

=== Einstellungen in Hyper-V

Funktionierende Einstellugen sind z.B.:  

- 8192 MB RAM  
- Secure Boot deaktivieren
- 4 cores
- 200 GB

_Nested Virtualization_ muss eingestellt werden, damit die Container und VMs IP Adressen per DHCP beziehen können: 

In einer Admin Powershell/CMD auf der Windows Maschine in der Hyper-V läuft folgendes eingeben: 

 Set-VMProcessor -VMName 'vmname' -ExposeVirtualizationExtensions $true

_MAC Address Spoofing_ in Hyper-V einstellen:

 Einstellungen -> Netzwerkkarte -> Erweiterte Features -> Haken bei _MAC Address Spoofing_ aktivieren

=== Dateisystem

Als Dateisystem wird ZFS genutzt. ZFS ist ein Copy-On-Write Dateisystem und bringt einige Vorteile mit, wie z.B. Kompression, Integritätschecks, Einrichtung von Pools mit Quotas etc.

ZFS muss bei der Installation ausgewählt werden. Steht nur eine Festplatte zur Verfügung, wird `RAID0` ausgewählt.

Links:

- https://pve.proxmox.com/wiki/ZFS_on_Linux
- https://arstechnica.com/information-technology/2020/05/zfs-101-understanding-zfs-storage-and-performance/

=== Storages

Bei der Verwendung von ZFS können _Pools_ erstellt werden. Diese verhalten sich ähnlich wie Partitionen, sind aber deutlich flexibler. Z.B. kann die Größe im laufenden Betrieb angepasst werden.

In einer Shell auf dem Proxmox Node als `root` einen neuen _Pool_ mit dem Namen `backups` erstellen:

 zfs create rpool/backups

Quota/Größe für den Pool auf 60G setzen: 

 zfs set quota=60G rpool/backups

Informationen über vorhandene Pools abfragen: 

 zfs get mounted,mountpoint,canmount rpool/backups
 zfs list -t all

=== Backups

Oben erstellen Pool für Backups nutzen. In der Weboberfläche von Proxmox:

 Datacenter -> Storage -> Add -> Directory -> backups eintragen -> Directory: /rpool/backups -> Add

*Achtung:* In einem Produktivsystem sollte sichergestellt sein, dass die Backups auf ein anderes Speichermedium verschoben bzw. initial gespeichert werden, da ansonsten bei einem Ausfall/Fehler auch die Backups verlohren gehen könnten.

Links:

https://forum.proxmox.com/threads/festplatte-backups-funktionieren-nicht.87867/#post-385077

==== Backups einrichten

In der Proxmox Weboberfläche:

 Datacenter -> Backups -> Add -> Container/VMs und Zeitpunkte auswählen

=== Netzwerkkonfigutaion

Bei der Installation von Proxmox wird automatisch eine Bridge `vmbr0` erstellt, welche das reguläre Interface z.B. `eht0` bridged. Die Bridge ist nötig, damit auch die Container bzw. VMs darüber Zugang zum Netzwerk haben.

In der Weboberfläche erhält man über _pve_ -> _Network_ eine Übersicht über die vorhandenen NICs. Hier können auch weitere Adapter hinzugefügt werden. 

*Achtung:* Wird die Konfiguration über die Weboberfläche geändert, überschreibt diese eine ggf. vorhanden Konfiguration in der Datei `/etc/network/interfaces`.

Links: 

- https://pve.proxmox.com/wiki/Network_Configuration

==== Subnetz

Es wird ein Subnetz erstellt, aus welchem die Container ihre IP Adresse beziehen. Der Grund hierfür ist zum einen, dass in einem Produktivsystem mit öffentlichen IP Adressen entweder für jeden Container eine separate IP Adresse vorhanden sein müsste oder ein Subnetz gebucht werden müsste. Des weiteren kann über das Subnetz sichergestellt werden, dass die Container nicht von außerhalt von Proxmox zugegriffen werden kann (Sicherheit).

Die neue Bridge `vmbr1` wird über die Weboberfläche erstellt, so dass ihr auch ein Name bzw. ID zugewiesen werden kann. Diese ist wichtig, um die Bridge in anderen Containern (z.B. DHCP) verwenden zu können.

Die weiter Konfiguration erfolgt in der Datei `/etc/network/interfaces`. Zusätzlich werden hier Firewallregeln für NAT eingetragen. 

Eine Beispiel Konfiguration findet sich hier:

https://github.com/qasch/proxmox-le/blob/main/node/interfaces

== VMs

Eine VM kann einfach über die Weboberfläche erstellt werden (_Create VM_). Vorher muss allerdings eine entsprechende ISO Datei in Prxomx hochgeladen werden:

 Datacenter -> local(pve) -> ISO Iamges

Bei der Erstellung auf die Wahl der richtigen Bridge achten! `vmbr0` wenn die VM *nicht* in das Subnetz soll, ansonsnten `vmbr1` auswählen.

=== Einstellung in Hyper-V

Bei der Verwendung von Hyper-V muss für jede VM die _KVM hardware virutalization_ in der Weboberfläche von Proxmox ausgeschaltet werden:

 VM -> Options -> Edit -> KVM hardware virutalization -> No

== Container

In der Regel verwenden wir in  Proxmox keine VMs sondern LXC Container. Diese sind ähnlich wie docker Container deutlich resourcenschonender als VMs. 

=== Container erstellen

Auch Container können entweder über die Weboberfläche (_Create VM_) oder die Shell erstellt werden. Anders als bei docker werden für LXC keine Images heruntergeladen, sondern Templates verwendet. Auch diese müssen zuvor in Proxmox heruntergeladen werden. Proxmox bietet fertige Templates an:

 Datacenter -> local(pve) -> CT Templates -> Templates

Nun kann über _Create CT_ ein Container erstellt werden. Auch hier sollte auf die Wahl der richtigen Bridge (`vmbr1`) geachtet werden. 

In einem Produktivsystem sollten alle Container und VMs über eine statische bzw. sich nicht ändernde IP Adresse verfügen. Diese kann entweder statisch bei der Installation oder über die Verwendung eines DHCP Servers (s.u.) erfolgen.

Die Container sollten nach einem Neustart von Proxmox automatisch neu gestartet werden. Dazu unter `Options` des jeweiligen Containers _Start at boot_ auf _Yes_ stellen_.

Links:

- https://pve.proxmox.com/wiki/Linux_Container
- https://linuxcontainers.org/
- https://www.redhat.com/de/topics/containers/whats-a-linux-container
- https://de.wikipedia.org/wiki/LXC

=== DHCP Server

Als DHCP Server wird _Kea_ verwendet. Andere DHCP Server sind natürlich auch möglich.

Als Template wird z.B. ein Ubuntu verwendet. In diesem Container wird das Paket `kea` installiert:

 apt install kea

Wichtig bei der Verwendung eines Subnetzes ist es, dass diesem Container *beide* Bridges zugewiesen werden. Nur so kann der DHCP Server IP Adressen für beide Netze bereitstellen. In unseren Fall scheint das nötig, da der DNS Server nicht in dem Subnetz ist und in der Konfiguration dieser DNS Server eingetragen ist. 

Die Bridge `vmbr0` sollte hier eine statische IP aus dem "öffentlichen" Netz erhalten, die Bridge `vmbr1` wird mit der IP Adresse der Bridge (`192.168.200.1`) konfiguriert. Hier wird kein Gateway angegeben.

Vielleicht gibt es hierfür auch eine andere Möglichkeit, da wir in einem Produktivsystem so eine weitere IP benötigen würden.

==== Konfiguration

Die Konfiguration erfolgt in der Datei `/etc/kea/kea-dhcp4.conf` (https://github.com/qasch/proxmox-le/blob/main/dhcp/kea-dhcp4.conf).

Bei der Angabe des Interface ist auch die korrekte Bezeichnung der Bridge zu achten. Hier muss der Name ID der Bridge angegeben werden (`net1`) und *nicht* die Bezeichnung der Bridge `vmbr1`.

Damit die Container statische IPs über den DHCP erhalten, müssen für diese die MAC Adressen z.B. mit dem Kommando `ip a` oder über die Weboberfläche von Proxmox (Reiter _Network_ im jeweiligen Container) ermittelt werden. Die MAC Adresse wird in der Konfiguration als `hw-address` unter `reservations` angegeben.

Nach dem Ändern der Konfiguration muss der Dienst neu gestartet werden:

 systemctl restart kea-dhcp4-server

Bei Problemen kann ein Blick in das Journal hilfreich sein:

 journalctl -u kea-dhcp4-server

Log von `kea` live beobachten:

 journalctl -u kea-dhcp4-server -f

Sollte es zu Problemen kommen, dass der Server nicht gestartet werden konnte weil eine Reservation nicht im Subnetz ist, ggf. Proxmox komplett neu starten und etwas warten. Könnte mit Hyper-V zusammenhängen...

Links:

- https://ubuntu.com/server/docs/how-to-install-and-configure-isc-kea

=== DNS Server

Als DNS Server kommt `bind9` in einem Ubuntu Container zum Einsatz.

 apt install bind9 bind9utils

Dem DNS Container wird die Standard Bridge `vmbr0` zugewiesen, da er auch von außen erreichbar sein soll. Der DNS Server benötigt eine statische IP. Die Vergabe erfolgt über DHCP bzw. den DHCP Container. Folgende Konfigurationsdateien werden bearbeitet:

==== /etc/bind/named.conf.options

Hier wird eigentlich nur der Forwarder eingetragen, welcher benutzt wird, sollte kein entsprechendr Eintrag vorhanden sein. Außerdem die rekursive Namensauflösung `recursion yes`.

https://github.com/qasch/proxmox-le/blob/main/dns/named.conf.options

==== /etc/bind/named.conf.local

Hier werden die Zonen definiert und die Dateien angegeben, welche die eigentlichen Definitionen enthalten.

https://github.com/qasch/proxmox-le/blob/main/dns/named.conf.local

==== /etc/bind/zones/pve.loc

Die Forward Looking Zone mit einem NS Eintrag für den/die Nameserver und den A Records der Clients.

https://github.com/qasch/proxmox-le/blob/main/dns/zones/pve.loc

==== /etc/bind/zones/pve.loc.rev

Die Reverse Looking Zone analog zu oben. IP Adressen aus dem Subnetz können abgekürzt angegeben werden, in dem nur das letzte Oktet eingetragen wird. Bei IP Adressen außerhalb des Subnetzes wird die gesamte IP angegeben.

https://github.com/qasch/proxmox-le/blob/main/dns/zones/pve.loc.rev

Neustart mittels:

 systemctl restart bind9

=== Proxy Server

Da sich die Container in einem Subnetz befinden, sind sie von außen nicht erreichbar. Um trotzdem z.B. auf einen Webserver zugreifen zu können wird ein _Reverse Proxy_ eingerichtet. Der Proxy könnte dann auch alle SSL-Zertifikate für die einzelnen Container bereitstellen. 

Der Proxy Container benötigt auch wieder beide Bridges. Die erste Bridge `vmbr0` benötigt eine statische IP (statisch vergeben oder per DHCP Server). Hierüber ist der Zugang zum Internet möglich, über die Bridge `vmbr1` können Anfragen von und zu den Containern verarbeitet werden.

Wir verweden den Webserver `nginx` als Reverse Proxy, Alternativen wie z.B. `traefik` sind aber auch möglich.

 apt install nginx

==== Konfiguration

Für jeden (Web)Server wird eine eigene Datei unter `/etc/nginx/sites-available` angelegt. Die Konfiguration ist bewusst sehr simpel gehalten und es erfolgt lediglich eine Weiterleitung der Anfrage über die Direktive `proxy_pass` an den jeweiligen Container. Denkbar ist aber auch eine komplexere Konfiguration mit SSL Zertifikaten, Redirect etc.

https://github.com/qasch/proxmox-le/blob/main/proxy/webserver.conf

*Wichtig:* Die Konfigurationsdateien müssen noch in das Verzeichnis `/etc/nginc/sites-enabled` versymlinkt werden:

 ln -s /etc/nginx/sites-available/webserver.conf /etc/nginx/sites-enabled/

Syntax Test der Konfiguration:

 nginx -t

Erneutes Einlesen der Konfiguration:

 systemctl reload ngin

=== Webserver

Einfacher Container mit einem installierten Webserver (`apache2` oder `nginx`) zum Testen der DHCP und DNS Konfiguration.

Vergabe der IP Adresse erfolgt über den DHCP Container, gleichzeitig kann so die Reverse Proxy Konfiguration und die DNS Konfiguration getestet werden.

Um mittels URL auf diesn Container zugreifen zu können, muss die IP des DNS Containers in die `/etc/resolv.conf` auf dem Rechner eingetragen werden, von welchem aus die Anfrage gestellt wird. Unter Windows nutzen wir die GUI. Achtung bei der Verwendung eines VPNs - richtige Netzwerkkarte auswählen.

== CLI Kommandos

Anzeige von IP und MAC Adressen:

 ip a
 ip -br a

Auf Ubuntu Systemen geht auch:

 netplan status

Aufruf einer Website aus einem Container/Server ohne grafische Oberfläche:

 curl localhost
 curl <ip-adresse>
 curl <url>

Anzeige der in einem Debian Paket enthaltenen Dateien:

 dpkg -L <paket>
 dpkg -L bat

Neustart (Node, Container, Linux):

 reboot
 systemctl reboot

DNS Einträge abfragen:

 host <url>
 dig <url>
 nslookup <url>

 ping <url>

Anzeige der zuletzt bzw. momentan am System angemeldeten Benutzern:

 who
 w
 last

=== Proxmox Kommandos

Auf dem Proxmox Node.

Anzeige aller Container:

 pct list

Starten eines Containers:

 pct start <ct-id>
 pct start 100

Container betreten:

 pct enter <ct-id>
 pct enter 100

